Cocktail.delete_all
Cocktail.create(name: "Martini", description: "", recipe: "3 ounces vodka, 1 teaspoon vermouth (French vermouth)", liquor: "Vodka", photo_url: "http://www.esquire.com/cm/esquire/images/eS/VodkaMartini-004-de1.jpg")
Cocktail.create(name: "Old Fashioned", description: "", recipe: "", liquor: "Whiskey", photo_url: "http://www.esquire.com/cm/esquire/images/G1/old-fashioned.jpg")
Cocktail.create(name: "Bay Breeze", description: "", recipe: "", liquor: "", photo_url: "http://21nogluten.files.wordpress.com/2011/12/mbb.jpg")
Cocktail.create(name: "Cape Cod", description: "", recipe: "2 parts vodka, 2 parts cranberry juice, 1 part orange juice", liquor: "Vodka", photo_url: "http://www.cocktailsdrinkrecipes.com/images/cape-cod.jpg")
Cocktail.create(name: "Cuba Libre", description: "", recipe: "", liquor: "2 ounces liquor, fill glass with Coca-Cola", photo_url: "http://www.esquire.com/cm/esquire/images/Xx/CubaLibre-002-de1.jpg")

Cocktail.create(name: "Hairy Navel", description: "", recipe: "1 ounce vodka, 1 ounce peach schnapps, orange juice to fill", liquor: "Vodka", photo_url: "http://0.tqn.com/d/cocktails/1/I/-/1/-/-/top_screwdriver.jpg")
Cocktail.create(name: "Dark & Stormy", description: "", recipe: "", liquor: "", photo_url: "")
Cocktail.create(name: "Highball", description: "", recipe: "2 ounces liquor, 2 to 4 ounces club soda", liquor: "", photo_url: "http://www.esquire.com/cm/esquire/images/1I/Highball-002-de1.jpg")
Cocktail.create(name: "Madras", description: "", recipe: "", liquor: "", photo_url: "")
Cocktail.create(name: "Tequila Sunrise", description: "", recipe: "", liquor: "", photo_url: "")
Cocktail.create(name: "Black Russian", description: "", recipe: "", liquor: "", photo_url: "")
Cocktail.create(name: "Godfather", description: "", recipe: "1.5 ounce Scotch, .5 ounce Amaretto", liquor: "Whiskey", photo_url: "http://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Godfather_cocktail.jpg/240px-Godfather_cocktail.jpg")
Cocktail.create(name: "Rusty Nail", description: "", recipe: "2 ounces Whiskey, .5 ounce Drambuie", liquor: "Whiskey", photo_url: "http://www.esquire.com/cm/esquire/images/vs/RustyNail-003-de1.jpg")
Cocktail.create(name: "Sazerac", description: "", recipe: "", liquor: "", photo_url: "http://liquor.s3.amazonaws.com/wp-content/uploads/2012/01/1.18.12_FA_The_Sazerac-290x290.jpg")
Cocktail.create(name: "White Russian", description: "Shake well with cracked ice, then strain into a chilled Old-Fashioned glass (it'll look less wicked than in a martini glass; that's important). Some folks build this one on the rocks, floating the cream on top. No.", recipe: "1.5 ounce vodka, .75 Kahlua coffee liquer, .75 ounces of cream", liquor: "", photo_url: "http://www.esquire.com/cm/esquire/images/Ns/WhiteRussian-002-de1.jpg")
Cocktail.create(name: "Dirty Martini", description: "This is a Martini for olive lovers. It can be served on the rocks, or chilled", recipe: "2.5 ounce vodka, 1 ounce dry vermouth, 1 ounce olive brine, garnish with olives", liquor: "", photo_url: "http://liquor.s3.amazonaws.com/wp-content/uploads/2011/04/Dirty-Martini-newest.jpg")
Cocktail.create(name: "Gibson", description: "", recipe: "2.5 ounces of vodka, .75 ounce dry vermouth, 3 to 5 cocktail onions", liquor: "", photo_url: "http://friendseat.com/file/pic/recipe/2012/03/34759.jpg")
Cocktail.create(name: "Manhattan", description: "", recipe: "", liquor: "Whiskey", photo_url: "http://www.esquire.com/cm/esquire/images/r4/esq-manhattan-lg.jpg")
Cocktail.create(name: "Cosmopolitan", description: "", recipe: "", liquor: "", photo_url: "")
Cocktail.create(name: "Jack Rose", description: "", recipe: "", liquor: "", photo_url: "")
Cocktail.create(name: "Long Island Iced Tea", description: "", recipe: "", liquor: "", photo_url: "")
Cocktail.create(name: "Millionaire", description: "", recipe: "", liquor: "Whiskey", photo_url: "http://www.esquire.com/cm/esquire/images/sh/esq-millionaire-lg.jpg")
Cocktail.create(name: "Air Mail", description: "", recipe: "2 ounces rum, .5 ounce lime juice, 1 teaspoon honey, 5 ounces Brut champagne", liquor: "Rum", photo_url: "http://www.esquire.com/cm/esquire/images/FH/AirMail-003-de1.jpg")
Cocktail.create(name: "Between the Sheets", description: "", recipe: "1 ounce rum, 1 ounce Cointreau, .5 ounce lemon juice, 1 ounce cognac", liquor: "Rum", photo_url: "http://www.esquire.com/cm/esquire/images/Dm/BetweentheSheets-003-de1.jpg")
Cocktail.create(name: "Boilermaker", description: "", recipe: "1 shot whiskey, 1 beer", liquor: "Whiskey", photo_url: "http://www.esquire.com/cm/esquire/images/SN/Boilermaker-002-de1.jpg")
Cocktail.create(name: "Chancellor", description: "", recipe: "2 ounces whiskey, 1 ounce ruby port, 1/2 ounce vermouth, 2 dashes orange bitters", liquor: "Whiskey", photo_url: "http://www.esquire.com/cm/esquire/images/HW/Chancellor-005-de1.jpg")
Cocktail.create(name: "El Presidente", description: "", recipe: "1.5 ounces rum, .5 ounce orange curacao, .75 ounce French vermouth, 1 dash grenadine", liquor: "Rum", photo_url: "http://www.esquire.com/cm/esquire/images/kJ/ElPresidente-007-de1.jpg")
Cocktail.create(name: "Mai Tai", description: "", recipe: "2 ounces rum, 1 ounce lime juice, .5 ounce orange curacao, .5 ounce orgeat syrup, .25 ounce simple syrup", liquor: "Rum", photo_url: "http://www.esquire.com/cm/esquire/images/lO/MaiTai-004-de1.jpg")
Cocktail.create(name: "Moscow Mule", description: "", recipe: ".5 ounce lime juice, 2 ounces vodka, 4 ounces ginger beer", liquor: "Vodka", photo_url: "http://www.esquire.com/cm/esquire/images/zL/MoscowMule-004-de1.jpg")
Cocktail.create(name: "Whiskey Sour", description: "", recipe: "2 ounces whiskey (usually bourbon), 2/3 ounce lemon juice, 1 teaspoon sugar", liquor: "Whiskey", photo_url: "http://www.esquire.com/cm/esquire/images/cy/WhiskeySour-001-de1.jpg")


Bar.create(name: "Dutch Kills", address: "27-24 Jackson Avenue, Queens, New York", bar_url: "http://dutchkillsbar.com/main/")
Bar.create(name: "Clover Club", address: "210 Smith Street, Brooklyn, New York", bar_url: "http://www.cloverclubny.com/")
